export type Outcome = 'HANDLED' | 'DETECTED' | 'UNHANDLED';

export interface Scenario {
  id: string;
  category: string;
  title: string;
  expectation: string;
  outcome: Outcome;
  note?: string;
}

export const SCENARIOS: Scenario[] = [
  { id: 'A1', category: 'Exactly-once', title: 'Crash after gateway call, before database write', expectation: 'Restart reconciles to the real outcome. Exactly one order.', outcome: 'HANDLED' },
  { id: 'A2', category: 'Exactly-once', title: 'Crash after intent row, before gateway call', expectation: 'Reconciler finds no order and marks it abandoned.', outcome: 'HANDLED' },
  { id: 'A3', category: 'Exactly-once', title: 'Crash between submit and settle', expectation: 'Reconciler settles to the real payment status.', outcome: 'HANDLED' },
  { id: 'A4', category: 'Exactly-once', title: 'Two workers claim the same attempt simultaneously', expectation: 'One wins the unique index, the other gets a clean duplicate result.', outcome: 'HANDLED' },
  { id: 'A5', category: 'Exactly-once', title: 'Duplicate webhook delivery, same event id', expectation: 'Second delivery is a no-op via the event dedup index.', outcome: 'HANDLED' },
  { id: 'A6', category: 'Exactly-once', title: 'Gateway rejects a receipt that already exists', expectation: 'Reconcile against the existing order. Never modify the receipt.', outcome: 'HANDLED' },
  { id: 'A7', category: 'Exactly-once', title: 'A dry run followed by a live run for the same attempt', expectation: 'The key is already consumed, so the live run cannot double it.', outcome: 'HANDLED' },
  { id: 'A8', category: 'Exactly-once', title: 'Gateway returns an error after the charge actually succeeded', expectation: 'Reconciler finds the order by receipt and records the truth.', outcome: 'HANDLED' },
  { id: 'A9', category: 'Exactly-once', title: 'Network timeout with an unknown outcome', expectation: 'Never assumed failed. Held until reconciled.', outcome: 'HANDLED' },
  { id: 'A10', category: 'Exactly-once', title: 'Different attempt number for the same cycle', expectation: 'A distinct key, so it is a distinct legitimate charge.', outcome: 'HANDLED' },

  { id: 'B1', category: 'Lifecycle races', title: 'Merchant write access revoked while a job is in flight', expectation: 'Checked immediately before the call, not only at proposal time.', outcome: 'HANDLED' },
  { id: 'B2', category: 'Lifecycle races', title: 'Kill switch tripped mid-run', expectation: 'Read fresh per attempt. No intent row written.', outcome: 'HANDLED' },
  { id: 'B3', category: 'Lifecycle races', title: 'Mandate expires between scheduling and execution', expectation: 'R-EXPIRY denies again at execution time.', outcome: 'HANDLED' },
  { id: 'B4', category: 'Lifecycle races', title: 'Subscription halts while a retry is scheduled', expectation: 'R-HALT denies again at execution time.', outcome: 'HANDLED' },
  { id: 'B5', category: 'Lifecycle races', title: 'Customer pays manually while a retry is scheduled', expectation: 'R-PAID refuses at both proposal and execution time.', outcome: 'HANDLED' },
  { id: 'B6', category: 'Lifecycle races', title: 'Mandate revoked by the customer between proposal and execution', expectation: 'Fresh state is read and re-evaluated before executing.', outcome: 'HANDLED' },
  { id: 'B7', category: 'Lifecycle races', title: 'Subscription amount changes between attempts', expectation: 'The stored intent amount is compared and a mismatch is refused loudly, never silently deduplicated.', outcome: 'HANDLED' },
  { id: 'B8', category: 'Lifecycle races', title: 'Subscription cancelled mid-cycle', expectation: 'R-HALT denies at proposal time.', outcome: 'HANDLED' },

  { id: 'C1', category: 'Classification', title: 'A decline code never seen before', expectation: 'UNKNOWN, one conservative attempt, surfaced on the dashboard.', outcome: 'HANDLED' },
  { id: 'C2', category: 'Classification', title: 'Reason and source disagree', expectation: 'UNKNOWN rather than a coin flip. The source lean is recorded, not acted on.', outcome: 'HANDLED' },
  { id: 'C3', category: 'Classification', title: 'error_source is business, meaning our own request was malformed', expectation: 'Logged as our bug and excluded from the attempt budget.', outcome: 'HANDLED' },
  { id: 'C4', category: 'Classification', title: 'Failed payment with every error field null', expectation: 'UNKNOWN. Must not throw.', outcome: 'HANDLED' },
  { id: 'C5', category: 'Classification', title: 'A hard decline followed by a success', expectation: 'State recovers, no stuck hard flag.', outcome: 'HANDLED' },
  { id: 'C6', category: 'Classification', title: 'The same reason string meaning different things per method', expectation: 'Bucketing keys on method and reason together.', outcome: 'HANDLED' },
  { id: 'C7', category: 'Classification', title: 'Amount above the additional-authentication threshold', expectation: 'No silent retry is possible. R-METHOD denies.', outcome: 'HANDLED' },
  { id: 'C8', category: 'Classification', title: 'Chronic soft declines across many cycles', expectation: 'R-CHRONIC stops retrying after a configurable number of cycles and leaves re-authorization as the path.', outcome: 'HANDLED' },

  { id: 'D1', category: 'Time and calendar', title: 'Retry proposed inside the 24 hour notification floor', expectation: 'R-PDN defers and returns an adjusted time.', outcome: 'HANDLED' },
  { id: 'D2', category: 'Time and calendar', title: 'Retry enqueued in the last ten minutes of the day for a next-day debit', expectation: 'Pushed to the day after.', outcome: 'HANDLED' },
  { id: 'D3', category: 'Time and calendar', title: 'Preferred time falls inside a peak execution window', expectation: 'R-WINDOW snaps forward to the next permitted window.', outcome: 'HANDLED' },
  { id: 'D4', category: 'Time and calendar', title: 'A customer whose payday is the 31st, in February', expectation: 'Clamped to the last day of the month.', outcome: 'HANDLED' },
  { id: 'D5', category: 'Time and calendar', title: 'Successes on the 1st and the 31st', expectation: 'Circular statistics. Must not average to the middle of the month.', outcome: 'HANDLED' },
  { id: 'D6', category: 'Time and calendar', title: 'Stored UTC, reasoned in IST, across midnight', expectation: 'Day of month reads IST, not UTC.', outcome: 'HANDLED' },
  { id: 'D7', category: 'Time and calendar', title: 'Boundary exactly at 24 hours, and one second under', expectation: 'Both sides tested, the legal side defined.', outcome: 'HANDLED' },
  { id: 'D8', category: 'Time and calendar', title: 'A scheduled job whose time passed while the worker was down', expectation: 'Re-validate the revocable and structural rules before executing a stale job.', outcome: 'HANDLED' },
  { id: 'D9', category: 'Time and calendar', title: 'Retry scheduled onto a bank holiday for e-mandate', expectation: 'Shifted T to T-1, or T-3 when both are holidays, with the shift recorded on the decision.', outcome: 'HANDLED' },

  { id: 'E1', category: 'Budget', title: 'Our attempt and an automatic retry in the same cycle', expectation: 'Both count against the network budget.', outcome: 'HANDLED' },
  { id: 'E2', category: 'Budget', title: 'Exactly at the budget limit', expectation: 'Tested at n-1, n and n+1.', outcome: 'HANDLED' },
  { id: 'E3', category: 'Budget', title: 'An attempt still unresolved after 36 hours', expectation: 'Budget held, not released. Settlement is slow.', outcome: 'HANDLED' },
  { id: 'E4', category: 'Budget', title: 'An attempt that crashed before submitting', expectation: 'Budget not spent, but only the reconciler can establish that.', outcome: 'HANDLED' },
  { id: 'E5', category: 'Budget', title: 'Budget counted across a cycle boundary', expectation: 'The cycle identifier resets it correctly.', outcome: 'HANDLED' },
  { id: 'E6', category: 'Budget', title: 'Backfilled historical attempts', expectation: 'Excluded from the live budget via counts_against_budget.', outcome: 'HANDLED' },
  { id: 'E7', category: 'Budget', title: 'e-mandate previous attempt still unconfirmed', expectation: 'Do not schedule a second attempt while one is in flight.', outcome: 'HANDLED' },

  { id: 'F1', category: 'Policy and agent', title: 'Agent returns malformed JSON', expectation: 'DEFER. Never a default action.', outcome: 'HANDLED' },
  { id: 'F2', category: 'Policy and agent', title: 'Agent proposes an action outside the enum', expectation: 'Rejected at validation, recorded as R-MALFORMED.', outcome: 'HANDLED' },
  { id: 'F3', category: 'Policy and agent', title: 'Agent proposes a retry on a hard decline', expectation: 'R-HARD denies cleanly and the denial is logged.', outcome: 'HANDLED' },
  { id: 'F4', category: 'Policy and agent', title: 'A proposal that trips several rules at once', expectation: 'First deny wins, and the reported rule is the most useful one.', outcome: 'HANDLED' },
  { id: 'F5', category: 'Policy and agent', title: 'Agent proposes a time in the past', expectation: 'R-PDN adjusts rather than erroring.', outcome: 'HANDLED' },
  { id: 'F6', category: 'Policy and agent', title: 'Agent API times out', expectation: 'DEFER after retry. Never a fallback action.', outcome: 'HANDLED' },
  { id: 'F7', category: 'Policy and agent', title: 'Model refuses the request', expectation: 'Treated as an invalid response and deferred.', outcome: 'HANDLED' },
  { id: 'F8', category: 'Policy and agent', title: 'Blast radius cap reached exactly at this attempt', expectation: 'R-BLAST denies, counting live intents per merchant.', outcome: 'HANDLED' },
  { id: 'F9', category: 'Policy and agent', title: 'Issuer degraded at execution time', expectation: 'R-DEGRADED defers rather than spending an attempt.', outcome: 'HANDLED' },
  { id: 'H1', category: 'Degradation', title: 'Two failures out of two on a low-volume issuer', expectation: 'A sample floor prevents a detector that fires constantly on thin data.', outcome: 'HANDLED' },
  { id: 'H2', category: 'Degradation', title: 'A small dip that is within sampling noise', expectation: 'A proportion test, not a raw ratio threshold.', outcome: 'HANDLED' },
  { id: 'H3', category: 'Degradation', title: 'One issuer degraded, another healthy', expectation: 'Signals are per issuer and method, never global.', outcome: 'HANDLED' },
  { id: 'H4', category: 'Degradation', title: 'The gateway saw the outage before we did', expectation: 'Reported as a negative lead time rather than hidden.', outcome: 'HANDLED' },
  { id: 'H5', category: 'Degradation', title: 'A repeated rollup opens duplicate signals', expectation: 'An open signal suppresses a second one until it resolves.', outcome: 'HANDLED' },
  { id: 'H6', category: 'Degradation', title: 'Cross-merchant pooling without disclosure', expectation: 'Pooling is opt-in per merchant via cross_merchant_signals, which defaults to false.', outcome: 'HANDLED' },
  { id: 'J1', category: 'Not yet built', title: 'Live gateway never exercised against Razorpay itself', expectation: 'Orders created and charged against the real API.', outcome: 'DETECTED', note: 'The client exists and its request shape, auth header, paise integers, notification timing, and error mapping are all covered by tests against a stubbed transport. It has never made a call to Razorpay, so credential handling, rate limits, and real error bodies remain unverified.' },
  { id: 'J2', category: 'Not yet built', title: 'Downtime webhooks from the gateway are never consumed', expectation: 'payment.downtime.started and .resolved feed the degradation signal.', outcome: 'HANDLED' },
  { id: 'J3', category: 'Not yet built', title: 'The decline taxonomy is unverified against real data', expectation: 'Every bucket confirmed by an observed outcome on a real merchant account.', outcome: 'UNHANDLED', note: 'All six mapped reasons come from public documentation and are marked verified: false. A wrong bucket spends a real attempt on a mandate that cannot be saved, and we cannot currently tell which entries are wrong.' },
  { id: 'J4', category: 'Not yet built', title: 'The liquidity model has never seen a real payment history', expectation: 'Windows inferred from genuine customer payment timestamps.', outcome: 'UNHANDLED', note: 'Circular clustering is unit-tested but has only ever run on synthetic day-of-month arrays. Whether it beats a fixed schedule on real customers is unmeasured, and the honest tiering means it may often fall back to the population default.' },
  { id: 'J5', category: 'Not yet built', title: 'The backtest has only run on test-mode data', expectation: 'A historical replay over a real merchant\'s failed payments.', outcome: 'DETECTED', note: 'The harness exists, is deterministic, and enforces the as-of cutoff structurally. It has only ever run on synthetic test-mode history, where every timing decision falls back to a population default and most declines are unmapped, so it currently measures the machinery rather than the policy.' },
  { id: 'W1', category: 'De-confliction', title: 'Debits from different merchants colliding on one account', expectation: 'Detected per customer within a collision window, and spread across the day.', outcome: 'HANDLED' },
  { id: 'W2', category: 'De-confliction', title: 'Different customers treated as colliding because the times match', expectation: 'Collisions are per customer key only.', outcome: 'HANDLED' },
  { id: 'W3', category: 'De-confliction', title: 'A merchant dropped so another can be paid', expectation: 'Every debit keeps a slot; the resolution is positive sum.', outcome: 'HANDLED' },
  { id: 'W4', category: 'De-confliction', title: 'A debit moved outside its own permitted window', expectation: 'Each debit stays inside its own earliest and latest, and outside peak.', outcome: 'HANDLED' },
  { id: 'W5', category: 'De-confliction', title: 'A small debit taking the slot a large one needs', expectation: 'Largest first, because clearing a larger debit needs more residual balance.', outcome: 'HANDLED' },
  { id: 'W6', category: 'De-confliction', title: 'A debit forced into an illegal slot to clear a collision', expectation: 'Reported as unresolvable and left where it was.', outcome: 'HANDLED' },
  { id: 'W7', category: 'De-confliction', title: 'Customers matched across merchants by guesswork', expectation: 'Only an explicit customer key participates, and pooling is opt-in per merchant. Unkeyed mandates are excluded, not inferred.', outcome: 'HANDLED' },
  { id: 'W8', category: 'De-confliction', title: 'De-confliction claimed without the data to do it', expectation: 'The report states plainly when no mandate carries a cross-merchant key.', outcome: 'HANDLED' },
  { id: 'U1', category: 'Live batch', title: 'Policy and exactly-once proven only in separate suites', expectation: 'A batch that drives both together, asserting distinct keys equal intents equal orders.', outcome: 'HANDLED' },
  { id: 'U2', category: 'Live batch', title: 'A batch leaving intents unsettled', expectation: 'No intent left in INTENDED or SUBMITTED after the run.', outcome: 'HANDLED' },
  { id: 'U3', category: 'Live batch', title: 'The kill switch ignored at batch scale', expectation: 'Engaging it stops every attempt in the batch, verified.', outcome: 'HANDLED' },
  { id: 'U4', category: 'Live batch', title: 'One mandate exceeding the network budget under load', expectation: 'No subscription accumulates more intents than the budget allows.', outcome: 'HANDLED' },
  { id: 'V1', category: 'Bank holidays', title: 'A holiday calendar that is never populated', expectation: 'Seeded from a migration and loaded from the database, with a cache.', outcome: 'HANDLED' },
  { id: 'V2', category: 'Bank holidays', title: 'Shifting a UPI charge that never needed shifting', expectation: 'Only e-mandate shifts; UPI settles every day.', outcome: 'HANDLED' },
  { id: 'V3', category: 'Bank holidays', title: 'A charge shifted forward instead of back', expectation: 'The shift only ever moves earlier, matching the bank rule.', outcome: 'HANDLED' },
  { id: 'V4', category: 'Bank holidays', title: 'An uncovered year silently treated as holiday-free', expectation: 'Reported as not covered, and no shift applied rather than a wrong one.', outcome: 'HANDLED' },
  { id: 'V5', category: 'Bank holidays', title: 'A shift applied without the merchant being able to see it', expectation: 'The decision explanation is appended with the reason for the shift.', outcome: 'HANDLED' },
  { id: 'T1', category: 'Control plane', title: 'A raw-body parser for webhooks silently emptying every other POST body', expectation: 'The parser keeps the raw bytes and parses the JSON, so handlers still receive a body.', outcome: 'HANDLED' },
  { id: 'T2', category: 'Control plane', title: 'A request to release the kill switch engaging it instead', expectation: 'A false value survives parsing, and the release path is distinct from the engage path.', outcome: 'HANDLED' },
  { id: 'T3', category: 'Control plane', title: 'Anyone able to release the kill switch', expectation: 'Engaging needs nothing, releasing needs a configured token. Failing safe is free, failing open is not.', outcome: 'HANDLED' },
  { id: 'T4', category: 'Control plane', title: 'Releasing the kill switch when no token is configured at all', expectation: 'Refused, rather than defaulting to open.', outcome: 'HANDLED' },
  { id: 'S1', category: 'Subscriptions path', title: 'Assuming an issued invoice can be charged by API', expectation: 'Verified against the Invoice API: create, update, issue, delete, cancel, fetch, notify. No charge endpoint exists.', outcome: 'HANDLED' },
  { id: 'S2', category: 'Subscriptions path', title: 'A domestic card queued for a manual charge nobody can make', expectation: 'Marked unchargeable with the reason, and ranked last.', outcome: 'HANDLED' },
  { id: 'S3', category: 'Subscriptions path', title: 'An already-paid or expired invoice offered for charging', expectation: 'Assessed and excluded, with the reason recorded.', outcome: 'HANDLED' },
  { id: 'S4', category: 'Subscriptions path', title: 'The queue ordered arbitrarily rather than by value', expectation: 'Chargeable first, then expected value, then soonest.', outcome: 'HANDLED' },
  { id: 'S5', category: 'Subscriptions path', title: 'Subscriptions merchants left entirely unaddressed', expectation: 'A ranked, timed, reasoned charge queue plus the invoice notification the API does allow.', outcome: 'DETECTED', note: 'The queue and the notification action exist. The charge itself still requires a human to press Attempt Charge in the Razorpay dashboard, because no API for it exists. Recovery on this path is assisted, not automated, and the product should say so rather than imply otherwise.' },
  { id: 'Q1', category: 'Backfill', title: 'Only the last page of history fetched', expectation: 'Pagination walks until a short page, with skip advancing correctly.', outcome: 'HANDLED' },
  { id: 'Q2', category: 'Backfill', title: 'A misbehaving API looping forever', expectation: 'A page ceiling stops the walk.', outcome: 'HANDLED' },
  { id: 'Q3', category: 'Backfill', title: 'A rate limit aborting the whole backfill', expectation: 'Retries 429 and 5xx with backoff, gives up on 4xx.', outcome: 'HANDLED' },
  { id: 'Q4', category: 'Backfill', title: 'Backfilled history counted against a live attempt budget', expectation: 'Rows carry source backfill and counts_against_budget false.', outcome: 'HANDLED' },
  { id: 'Q5', category: 'Backfill', title: 'Re-running the backfill doubling the history', expectation: 'Deduplicated on the gateway payment id.', outcome: 'HANDLED' },
  { id: 'Q6', category: 'Backfill', title: 'A payment with nothing to group it under silently dropped', expectation: 'Skipped and counted, not silently discarded.', outcome: 'HANDLED' },
  { id: 'R1', category: 'Nightly sweep', title: 'Risk only detected after a charge fails', expectation: 'A forward sweep scores active mandates and flags expiry and degradation before any failure.', outcome: 'HANDLED' },
  { id: 'R2', category: 'Nightly sweep', title: 'The same mandate rescored on every tick', expectation: 'A minimum interval between scorings, honoured per mandate.', outcome: 'HANDLED' },
  { id: 'R3', category: 'Nightly sweep', title: 'One merchant sweep touching another merchant data', expectation: 'The sweep is scopeable per merchant.', outcome: 'HANDLED' },
  { id: 'R4', category: 'Nightly sweep', title: 'Sweeping mandates that are already halted or cancelled', expectation: 'Excluded by status.', outcome: 'HANDLED' },
  { id: 'R5', category: 'Nightly sweep', title: 'The injected clock disagreeing with the database clock', expectation: 'The sweep stamps scored_at with the clock it was given, so it stays replayable.', outcome: 'HANDLED' },
  { id: 'P1', category: 'CSV import', title: 'A quoted field containing a comma shifts every column', expectation: 'A real CSV parser, with quoted fields, escaped quotes and embedded newlines covered.', outcome: 'HANDLED' },
  { id: 'P2', category: 'CSV import', title: 'Excel byte order mark corrupting the first header', expectation: 'The BOM is stripped before the header is read.', outcome: 'HANDLED' },
  { id: 'P3', category: 'CSV import', title: 'A ragged row silently shifting values into the wrong columns', expectation: 'Refused with the line number, never partially applied.', outcome: 'HANDLED' },
  { id: 'P4', category: 'CSV import', title: 'A header we do not recognise dropped without trace', expectation: 'Unrecognised columns are listed in the report.', outcome: 'HANDLED' },
  { id: 'P5', category: 'CSV import', title: 'Rupee-formatted amounts read as paise', expectation: 'A decimal amount is converted, an integer is treated as paise, and an unreadable one skips the row.', outcome: 'HANDLED' },
  { id: 'P6', category: 'CSV import', title: 'Re-importing the same export doubling the history', expectation: 'Deduplicated on the gateway payment id.', outcome: 'HANDLED' },
  { id: 'P7', category: 'CSV import', title: 'Imported history counted against a live attempt budget', expectation: 'Imported rows carry counts_against_budget false.', outcome: 'HANDLED' },
  { id: 'P8', category: 'CSV import', title: 'An unknown decline code guessed into a bucket to look complete', expectation: 'Left UNKNOWN and reported, even when it makes the analysis look less finished.', outcome: 'HANDLED' },
  { id: 'N1', category: 'Evaluation', title: 'An off-policy estimate quoted from a deterministic logger', expectation: 'Refused outright, because deterministic logs carry no counterfactual information.', outcome: 'HANDLED' },
  { id: 'N2', category: 'Evaluation', title: 'An estimate dominated by a handful of high-weight rows', expectation: 'Effective sample size reported beside every estimate, with a floor below which it is not quoted.', outcome: 'HANDLED' },
  { id: 'N3', category: 'Evaluation', title: 'Unbounded importance weights blowing up the estimate', expectation: 'Weights clipped, and the number clipped is reported.', outcome: 'HANDLED' },
  { id: 'N4', category: 'Evaluation', title: 'No exploration, so no support ever accumulates', expectation: 'The allocator takes a non-first-choice slot on a configurable fraction of decisions and records the propensity.', outcome: 'HANDLED' },
  { id: 'N5', category: 'Evaluation', title: 'Exploration spending an attempt on an illegal slot', expectation: 'Exploration only ever picks among slots the allocator ranked, and the policy engine still checks the result.', outcome: 'HANDLED' },
  { id: 'N6', category: 'Evaluation', title: 'An off-policy number reported before any outcome settled', expectation: 'Reports no support and explains why, rather than printing a figure.', outcome: 'HANDLED' },
  { id: 'M1', category: 'Batch', title: 'Arms compared on different populations', expectation: 'Both arms run the identical mandate set, so the denominators match exactly.', outcome: 'HANDLED' },
  { id: 'M2', category: 'Batch', title: 'A result that cannot be reproduced', expectation: 'Fixed seed, deterministic across runs, asserted by test.', outcome: 'HANDLED' },
  { id: 'M3', category: 'Batch', title: 'Wait treated as give up', expectation: 'A HOLD advances the clock rather than abandoning the mandate.', outcome: 'HANDLED' },
  { id: 'M4', category: 'Batch', title: 'A worse halt rate hidden behind a better efficiency number', expectation: 'The tradeoff is computed and printed, with the lifetime cost against the efficiency gain.', outcome: 'HANDLED' },
  { id: 'M5', category: 'Batch', title: 'A hardcoded conclusion contradicting the computed numbers', expectation: 'Favourable or unfavourable is derived, and a test asserts exactly one appears.', outcome: 'HANDLED' },
  { id: 'M6', category: 'Batch', title: 'Simulated numbers presented as real', expectation: 'Labelled simulated in the first two hundred characters, with the generative model printed in full.', outcome: 'HANDLED' },
  { id: 'M7', category: 'Batch', title: 'The batch never ran through the real executor', expectation: 'A live batch drives every attempt through intent rows, idempotency keys and settlement, asserting one order per attempt.', outcome: 'HANDLED' },
  { id: 'L1', category: 'Gateway', title: 'A live key used while the mode says test', expectation: 'Refuse at construction rather than charging real money in a test run.', outcome: 'HANDLED' },
  { id: 'L2', category: 'Gateway', title: 'A test key used while the mode says live', expectation: 'Refuse at construction.', outcome: 'HANDLED' },
  { id: 'L3', category: 'Gateway', title: 'Charging a subscription with no recurring token recorded', expectation: 'Raise before any HTTP call is made.', outcome: 'HANDLED' },
  { id: 'L4', category: 'Gateway', title: 'A duplicate receipt rejection mistaken for a generic error', expectation: 'Mapped to DuplicateReceiptError so the executor reconciles instead of retrying.', outcome: 'HANDLED' },
  { id: 'L5', category: 'Gateway', title: 'An unparseable response body returning undefined', expectation: 'Raises a typed error rather than proceeding on nothing.', outcome: 'HANDLED' },
  { id: 'L6', category: 'Gateway', title: 'Credentials leaking into a URL or a log line', expectation: 'Auth travels in a header only, and the logger redacts secrets.', outcome: 'HANDLED' },
  { id: 'L7', category: 'Gateway', title: 'Rupee floats sent where paise integers are required', expectation: 'Amount asserted to be an integer in paise.', outcome: 'HANDLED' },
  { id: 'K1', category: 'Backtest', title: 'The liquidity model sees payments from after the decision point', expectation: 'The loader refuses any row at or after the cutoff.', outcome: 'HANDLED' },
  { id: 'K2', category: 'Backtest', title: 'A row exactly at the cutoff leaks in', expectation: 'The cutoff is exclusive, and a test covers the boundary.', outcome: 'HANDLED' },
  { id: 'K3', category: 'Backtest', title: 'The same attempt counted once per failure that precedes it', expectation: 'Attempts are deduplicated by id, not summed per decision point.', outcome: 'HANDLED' },
  { id: 'K4', category: 'Backtest', title: 'A timing adjustment reported as a refusal', expectation: 'A defer that only moves the clock still authorises the attempt.', outcome: 'HANDLED' },
  { id: 'K5', category: 'Backtest', title: 'An approved non-retry action reported as a rule refusal', expectation: 'Labelled by the action chosen, never by R-OK.', outcome: 'HANDLED' },
  { id: 'K6', category: 'Backtest', title: 'The report claims a recovery figure it cannot support', expectation: 'It states plainly that history holds no outcome for an attempt never made.', outcome: 'HANDLED' },
  { id: 'K7', category: 'Backtest', title: 'A weak timing model presented as a working one', expectation: 'The report says so when most decisions fell back to a population default.', outcome: 'HANDLED' },
  { id: 'I1', category: 'Fixes', title: 'A paid cycle is described as out of attempts instead of paid', expectation: 'R-PAID outranks R-BUDGET so the merchant sees the true reason.', outcome: 'HANDLED' },
  { id: 'I2', category: 'Fixes', title: 'The chronic-decline limit cannot be switched off', expectation: 'Setting the limit to zero disables the rule.', outcome: 'HANDLED' },
  { id: 'I3', category: 'Fixes', title: 'A bank holiday shift silently changes the time of day', expectation: 'The shift preserves the time and records what it did.', outcome: 'HANDLED' },
  { id: 'I4', category: 'Fixes', title: 'Every Saturday treated as a bank holiday', expectation: 'Only the second and fourth Saturday, plus every Sunday.', outcome: 'HANDLED' },
  { id: 'G1', category: 'Stale decisions', title: 'Timing rules re-checked at execution would always fail', expectation: 'The notification lead time was satisfied when the attempt was scheduled, so it is not re-checked.', outcome: 'HANDLED' },
  { id: 'G2', category: 'Stale decisions', title: 'A revoked decision is picked up again on the next pass', expectation: 'The original decision is marked revoked so it is not re-selected.', outcome: 'HANDLED' },
  { id: 'G3', category: 'Stale decisions', title: 'The reason an attempt was cancelled is not visible to the merchant', expectation: 'The revocation is written as its own decision row with the rule that stopped it.', outcome: 'HANDLED' },
  { id: 'F10', category: 'Policy and agent', title: 'Dry run bypassed at one call site', expectation: 'Enforced inside the executor so no call site can bypass it.', outcome: 'HANDLED' },
];

export function scorecard(scenarios: Scenario[] = SCENARIOS) {
  const counts = { HANDLED: 0, DETECTED: 0, UNHANDLED: 0 };
  for (const s of scenarios) counts[s.outcome] += 1;
  return { total: scenarios.length, ...counts };
}
