export type Outcome = 'HANDLED' | 'DETECTED' | 'UNHANDLED';

export interface Scenario {
  id: string;
  category: string;
  title: string;
  expectation: string;
  outcome: Outcome;
  note?: string;
}

export const SCENARIOS: Scenario[] = [
  { id: 'A1', category: 'Exactly-once', title: 'Crash after gateway call, before database write', expectation: 'Restart reconciles to the real outcome. Exactly one order.', outcome: 'HANDLED' },
  { id: 'A2', category: 'Exactly-once', title: 'Crash after intent row, before gateway call', expectation: 'Reconciler finds no order and marks it abandoned.', outcome: 'HANDLED' },
  { id: 'A3', category: 'Exactly-once', title: 'Crash between submit and settle', expectation: 'Reconciler settles to the real payment status.', outcome: 'HANDLED' },
  { id: 'A4', category: 'Exactly-once', title: 'Two workers claim the same attempt simultaneously', expectation: 'One wins the unique index, the other gets a clean duplicate result.', outcome: 'HANDLED' },
  { id: 'A5', category: 'Exactly-once', title: 'Duplicate webhook delivery, same event id', expectation: 'Second delivery is a no-op via the event dedup index.', outcome: 'HANDLED' },
  { id: 'A6', category: 'Exactly-once', title: 'Gateway rejects a receipt that already exists', expectation: 'Reconcile against the existing order. Never modify the receipt.', outcome: 'HANDLED' },
  { id: 'A7', category: 'Exactly-once', title: 'A dry run followed by a live run for the same attempt', expectation: 'The key is already consumed, so the live run cannot double it.', outcome: 'HANDLED' },
  { id: 'A8', category: 'Exactly-once', title: 'Gateway returns an error after the charge actually succeeded', expectation: 'Reconciler finds the order by receipt and records the truth.', outcome: 'HANDLED' },
  { id: 'A9', category: 'Exactly-once', title: 'Network timeout with an unknown outcome', expectation: 'Never assumed failed. Held until reconciled.', outcome: 'HANDLED' },
  { id: 'A10', category: 'Exactly-once', title: 'Different attempt number for the same cycle', expectation: 'A distinct key, so it is a distinct legitimate charge.', outcome: 'HANDLED' },

  { id: 'B1', category: 'Lifecycle races', title: 'Merchant write access revoked while a job is in flight', expectation: 'Checked immediately before the call, not only at proposal time.', outcome: 'HANDLED' },
  { id: 'B2', category: 'Lifecycle races', title: 'Kill switch tripped mid-run', expectation: 'Read fresh per attempt. No intent row written.', outcome: 'HANDLED' },
  { id: 'B3', category: 'Lifecycle races', title: 'Mandate expires between scheduling and execution', expectation: 'R-EXPIRY denies again at execution time.', outcome: 'HANDLED' },
  { id: 'B4', category: 'Lifecycle races', title: 'Subscription halts while a retry is scheduled', expectation: 'R-HALT denies again at execution time.', outcome: 'HANDLED' },
  { id: 'B5', category: 'Lifecycle races', title: 'Customer pays manually while a retry is scheduled', expectation: 'R-PAID refuses at both proposal and execution time.', outcome: 'HANDLED' },
  { id: 'B6', category: 'Lifecycle races', title: 'Mandate revoked by the customer between proposal and execution', expectation: 'Fresh state is read and re-evaluated before executing.', outcome: 'HANDLED' },
  { id: 'B7', category: 'Lifecycle races', title: 'Subscription amount changes between attempts', expectation: 'The stored intent amount is compared and a mismatch is refused loudly, never silently deduplicated.', outcome: 'HANDLED' },
  { id: 'B8', category: 'Lifecycle races', title: 'Subscription cancelled mid-cycle', expectation: 'R-HALT denies at proposal time.', outcome: 'HANDLED' },

  { id: 'C1', category: 'Classification', title: 'A decline code never seen before', expectation: 'UNKNOWN, one conservative attempt, surfaced on the dashboard.', outcome: 'HANDLED' },
  { id: 'C2', category: 'Classification', title: 'Reason and source disagree', expectation: 'UNKNOWN rather than a coin flip. The source lean is recorded, not acted on.', outcome: 'HANDLED' },
  { id: 'C3', category: 'Classification', title: 'error_source is business, meaning our own request was malformed', expectation: 'Logged as our bug and excluded from the attempt budget.', outcome: 'HANDLED' },
  { id: 'C4', category: 'Classification', title: 'Failed payment with every error field null', expectation: 'UNKNOWN. Must not throw.', outcome: 'HANDLED' },
  { id: 'C5', category: 'Classification', title: 'A hard decline followed by a success', expectation: 'State recovers, no stuck hard flag.', outcome: 'HANDLED' },
  { id: 'C6', category: 'Classification', title: 'The same reason string meaning different things per method', expectation: 'Bucketing keys on method and reason together.', outcome: 'HANDLED' },
  { id: 'C7', category: 'Classification', title: 'Amount above the additional-authentication threshold', expectation: 'No silent retry is possible. R-METHOD denies.', outcome: 'HANDLED' },
  { id: 'C8', category: 'Classification', title: 'Chronic soft declines across many cycles', expectation: 'R-CHRONIC stops retrying after a configurable number of cycles and leaves re-authorization as the path.', outcome: 'HANDLED' },

  { id: 'D1', category: 'Time and calendar', title: 'Retry proposed inside the 24 hour notification floor', expectation: 'R-PDN defers and returns an adjusted time.', outcome: 'HANDLED' },
  { id: 'D2', category: 'Time and calendar', title: 'Retry enqueued in the last ten minutes of the day for a next-day debit', expectation: 'Pushed to the day after.', outcome: 'HANDLED' },
  { id: 'D3', category: 'Time and calendar', title: 'Preferred time falls inside a peak execution window', expectation: 'R-WINDOW snaps forward to the next permitted window.', outcome: 'HANDLED' },
  { id: 'D4', category: 'Time and calendar', title: 'A customer whose payday is the 31st, in February', expectation: 'Clamped to the last day of the month.', outcome: 'HANDLED' },
  { id: 'D5', category: 'Time and calendar', title: 'Successes on the 1st and the 31st', expectation: 'Circular statistics. Must not average to the middle of the month.', outcome: 'HANDLED' },
  { id: 'D6', category: 'Time and calendar', title: 'Stored UTC, reasoned in IST, across midnight', expectation: 'Day of month reads IST, not UTC.', outcome: 'HANDLED' },
  { id: 'D7', category: 'Time and calendar', title: 'Boundary exactly at 24 hours, and one second under', expectation: 'Both sides tested, the legal side defined.', outcome: 'HANDLED' },
  { id: 'D8', category: 'Time and calendar', title: 'A scheduled job whose time passed while the worker was down', expectation: 'Re-validate the revocable and structural rules before executing a stale job.', outcome: 'HANDLED' },
  { id: 'D9', category: 'Time and calendar', title: 'Retry scheduled onto a bank holiday for e-mandate', expectation: 'Shifted T to T-1, or T-3 when both are holidays, with the shift recorded on the decision.', outcome: 'HANDLED' },

  { id: 'E1', category: 'Budget', title: 'Our attempt and an automatic retry in the same cycle', expectation: 'Both count against the network budget.', outcome: 'HANDLED' },
  { id: 'E2', category: 'Budget', title: 'Exactly at the budget limit', expectation: 'Tested at n-1, n and n+1.', outcome: 'HANDLED' },
  { id: 'E3', category: 'Budget', title: 'An attempt still unresolved after 36 hours', expectation: 'Budget held, not released. Settlement is slow.', outcome: 'HANDLED' },
  { id: 'E4', category: 'Budget', title: 'An attempt that crashed before submitting', expectation: 'Budget not spent, but only the reconciler can establish that.', outcome: 'HANDLED' },
  { id: 'E5', category: 'Budget', title: 'Budget counted across a cycle boundary', expectation: 'The cycle identifier resets it correctly.', outcome: 'HANDLED' },
  { id: 'E6', category: 'Budget', title: 'Backfilled historical attempts', expectation: 'Excluded from the live budget via counts_against_budget.', outcome: 'HANDLED' },
  { id: 'E7', category: 'Budget', title: 'e-mandate previous attempt still unconfirmed', expectation: 'Do not schedule a second attempt while one is in flight.', outcome: 'HANDLED' },

  { id: 'F1', category: 'Policy and agent', title: 'Agent returns malformed JSON', expectation: 'DEFER. Never a default action.', outcome: 'HANDLED' },
  { id: 'F2', category: 'Policy and agent', title: 'Agent proposes an action outside the enum', expectation: 'Rejected at validation, recorded as R-MALFORMED.', outcome: 'HANDLED' },
  { id: 'F3', category: 'Policy and agent', title: 'Agent proposes a retry on a hard decline', expectation: 'R-HARD denies cleanly and the denial is logged.', outcome: 'HANDLED' },
  { id: 'F4', category: 'Policy and agent', title: 'A proposal that trips several rules at once', expectation: 'First deny wins, and the reported rule is the most useful one.', outcome: 'HANDLED' },
  { id: 'F5', category: 'Policy and agent', title: 'Agent proposes a time in the past', expectation: 'R-PDN adjusts rather than erroring.', outcome: 'HANDLED' },
  { id: 'F6', category: 'Policy and agent', title: 'Agent API times out', expectation: 'DEFER after retry. Never a fallback action.', outcome: 'HANDLED' },
  { id: 'F7', category: 'Policy and agent', title: 'Model refuses the request', expectation: 'Treated as an invalid response and deferred.', outcome: 'HANDLED' },
  { id: 'F8', category: 'Policy and agent', title: 'Blast radius cap reached exactly at this attempt', expectation: 'R-BLAST denies, counting live intents per merchant.', outcome: 'HANDLED' },
  { id: 'F9', category: 'Policy and agent', title: 'Issuer degraded at execution time', expectation: 'R-DEGRADED defers rather than spending an attempt.', outcome: 'HANDLED' },
  { id: 'H1', category: 'Degradation', title: 'Two failures out of two on a low-volume issuer', expectation: 'A sample floor prevents a detector that fires constantly on thin data.', outcome: 'HANDLED' },
  { id: 'H2', category: 'Degradation', title: 'A small dip that is within sampling noise', expectation: 'A proportion test, not a raw ratio threshold.', outcome: 'HANDLED' },
  { id: 'H3', category: 'Degradation', title: 'One issuer degraded, another healthy', expectation: 'Signals are per issuer and method, never global.', outcome: 'HANDLED' },
  { id: 'H4', category: 'Degradation', title: 'The gateway saw the outage before we did', expectation: 'Reported as a negative lead time rather than hidden.', outcome: 'HANDLED' },
  { id: 'H5', category: 'Degradation', title: 'A repeated rollup opens duplicate signals', expectation: 'An open signal suppresses a second one until it resolves.', outcome: 'HANDLED' },
  { id: 'H6', category: 'Degradation', title: 'Cross-merchant pooling without disclosure', expectation: 'Pooling is opt-in per merchant via cross_merchant_signals, which defaults to false.', outcome: 'HANDLED' },
  { id: 'J1', category: 'Not yet built', title: 'Live gateway never exercised against Razorpay itself', expectation: 'Orders created and charged against the real API.', outcome: 'DETECTED', note: 'The client now runs against a real Razorpay account: authentication, pagination, order creation, and real error bodies are verified, and genuine failed payments have been pulled through the backfill and classified. The recurring charge write is still unproven because the account has no recurring provisioning, so the charge path remains stubbed-transport only.' },
  { id: 'J2', category: 'Not yet built', title: 'Downtime webhooks from the gateway are never consumed', expectation: 'payment.downtime.started and .resolved feed the degradation signal.', outcome: 'HANDLED' },
  { id: 'J3', category: 'Not yet built', title: 'The decline taxonomy is unverified against real data', expectation: 'Every bucket confirmed by an observed outcome on a real merchant account.', outcome: 'UNHANDLED', note: 'Seven mapped reasons, all marked verified: false. Six come from public documentation; server_error was observed on a real account, which confirms the code exists but not that SOFT_TRANSIENT is the right bucket for it. Verification requires retry outcomes, which need a chargeable mandate. A wrong bucket spends a real attempt on a mandate that cannot be saved.' },
  { id: 'J4', category: 'Not yet built', title: 'The liquidity model has never seen a real payment history', expectation: 'Windows inferred from genuine customer payment timestamps.', outcome: 'UNHANDLED', note: 'Circular clustering is unit-tested but has only ever run on synthetic day-of-month arrays. Whether it beats a fixed schedule on real customers is unmeasured, and the honest tiering means it may often fall back to the population default.' },
  { id: 'J5', category: 'Not yet built', title: 'The backtest has only run on test-mode data', expectation: 'A historical replay over a real merchant\'s failed payments.', outcome: 'DETECTED', note: 'The harness exists, is deterministic, and enforces the as-of cutoff structurally. It has only ever run on synthetic test-mode history, where every timing decision falls back to a population default and most declines are unmapped, so it currently measures the machinery rather than the policy.' },
  { id: 'AG8', category: 'Agent', title: 'The model proposes contacting a customer who cancelled', expectation: 'R-HARD denies contact on HARD_CUSTOMER regardless of what the agent proposed.', outcome: 'HANDLED' },
  { id: 'AG9', category: 'Agent', title: 'A reasoning model is starved of tokens and returns nothing', expectation: 'Token budget leaves room for models that think before answering.', outcome: 'HANDLED' },
  { id: 'AG6', category: 'Agent', title: 'A key pasted into the wrong provider slot breaks every decision', expectation: 'A key whose shape does not match the provider is ignored and the next usable provider is chosen.', outcome: 'HANDLED' },
  { id: 'AG7', category: 'Agent', title: 'An empty or whitespace key selects a dead provider', expectation: 'A blank key is treated as absent.', outcome: 'HANDLED' },
  { id: 'AG1', category: 'Agent', title: 'The agent is locked to one paid vendor', expectation: 'Any OpenAI-compatible provider, including free and local ones, can drive the agent.', outcome: 'HANDLED' },
  { id: 'AG2', category: 'Agent', title: 'A weaker model returns prose instead of a proposal', expectation: 'Non-JSON and fenced or chattered output is recovered or rejected, never passed through.', outcome: 'HANDLED' },
  { id: 'AG3', category: 'Agent', title: 'A model invents an action outside the allowed set', expectation: 'The proposal is rejected before the policy engine ever sees it.', outcome: 'HANDLED' },
  { id: 'AG4', category: 'Agent', title: 'A provider outage stops the recovery loop', expectation: 'An http, network or quota failure degrades to the deterministic allocator plan.', outcome: 'HANDLED' },
  { id: 'AG5', category: 'Agent', title: 'A decision cannot be traced to the model that proposed it', expectation: 'Every outcome carries the model name and prompt version.', outcome: 'HANDLED' },
  { id: 'LP9', category: 'Landing page', title: 'The wordmark disappears behind the scenery at some screen ratios', expectation: 'The brand sits above scene imagery, and scenery is capped against viewport height as well as width.', outcome: 'HANDLED' },
  { id: 'LP10', category: 'Landing page', title: 'The same destination is listed twice in one navigation', expectation: 'No navigation repeats a link.', outcome: 'HANDLED' },
  { id: 'LP7', category: 'Landing page', title: 'The header reserves space for a control that was removed, clipping the call to action', expectation: 'The header wraps rather than clipping, and no layout column is reserved for a deleted control.', outcome: 'HANDLED' },
  { id: 'LP8', category: 'Landing page', title: 'A destination exists but cannot be reached from the top of the page', expectation: 'Proof, docs, dashboard and sign-up are all reachable from the primary navigation.', outcome: 'HANDLED' },
  { id: 'LP1', category: 'Landing page', title: 'Navigation links point at targets that cannot be scrolled to', expectation: 'Every anchor resolves to a real element outside the animated stage.', outcome: 'HANDLED' },
  { id: 'LP2', category: 'Landing page', title: 'The calls to action live inside a panel that starts invisible', expectation: 'Every call to action sits in always-visible content that needs no script and no scrolling.', outcome: 'HANDLED' },
  { id: 'LP3', category: 'Landing page', title: 'A control is shipped that does nothing when pressed', expectation: 'No dead controls remain on the page.', outcome: 'HANDLED' },
  { id: 'LP4', category: 'Landing page', title: 'The page states a rule count the engine contradicts', expectation: 'The published count is asserted against the policy engine.', outcome: 'HANDLED' },
  { id: 'LP5', category: 'Landing page', title: 'Type is sized for one screen width and breaks between breakpoints', expectation: 'Display type scales fluidly from a single clamp rather than by breakpoint overrides.', outcome: 'HANDLED' },
  { id: 'LP6', category: 'Landing page', title: 'A phone gets a desktop choreography it cannot perform', expectation: 'Narrow screens drop the scroll sequence and read the same story as static content.', outcome: 'HANDLED' },
  { id: 'DC1', category: 'Documentation', title: 'The documentation drifts from the code it describes', expectation: 'Rules, buckets, interventions and gaps are read out of the running source at request time.', outcome: 'HANDLED' },
  { id: 'UI1', category: 'Design system', title: 'The marketing page and the product drift into two different looks', expectation: 'One token file defines the palette, type scale and controls, and both stylesheets import it.', outcome: 'HANDLED' },
  { id: 'UI2', category: 'Design system', title: 'The display font is requested from a host that blocks cross-origin use', expectation: 'No font is loaded from a host without CORS headers, so the intended face actually renders.', outcome: 'HANDLED' },
  { id: 'UI3', category: 'Design system', title: 'Headlines ask for a weight the display face does not ship, and the browser fakes it', expectation: 'Display type only ever requests a weight the loaded face provides.', outcome: 'HANDLED' },
  { id: 'UI4', category: 'Design system', title: 'A control disappears because it matches the surface it sits on', expectation: 'Button contrast is derived from its surface rather than hand tagged.', outcome: 'HANDLED' },
  { id: 'UI5', category: 'Accessibility', title: 'Badge and hint colours fall below the readable threshold', expectation: 'Every shipped colour pair clears WCAG AA for normal text, asserted in tests.', outcome: 'HANDLED' },
  { id: 'UI6', category: 'Accessibility', title: 'Navigation vanishes on a phone, stranding the visitor on one page', expectation: 'The product nav scrolls on narrow screens instead of being hidden.', outcome: 'HANDLED' },
  { id: 'TI1', category: 'Test isolation', title: 'Running the dev stack makes the test suite fail at random', expectation: 'Tests run against their own database, so a live worker cannot corrupt them.', outcome: 'HANDLED' },
  { id: 'PR1', category: 'Legibility', title: 'A reviewer cannot tell in a minute whether any of this is real', expectation: 'One page assembles the arms table, a defended decision, a refusal, the escalation loop and the open gaps from live data.', outcome: 'HANDLED' },
  { id: 'PR2', category: 'Legibility', title: 'The proof is a static claim that cannot be re-run', expectation: 'The whole batch can be re-run from the page and the numbers rebuild from the database.', outcome: 'HANDLED' },
  { id: 'PR3', category: 'Legibility', title: 'The weaknesses are omitted from the summary', expectation: 'Unmapped share, unhandled scenarios and the simulated-money flag appear on the same page as the headline.', outcome: 'HANDLED' },
  { id: 'PR4', category: 'Legibility', title: 'Surfaces exist but cannot be reached from one another', expectation: 'Landing, proof, connect, mandates and dashboard all link to each other on one origin.', outcome: 'HANDLED' },
  { id: 'TR1', category: 'Explainability', title: 'A merchant cannot find out why one specific charge was timed the way it was', expectation: 'Every decision has a trace from decline through model, allocator, agent and rule to outcome.', outcome: 'HANDLED' },
  { id: 'TR2', category: 'Explainability', title: 'A recovery claim cannot be compared to what the default would have done', expectation: 'Each retry decision carries a counterfactual against the T+1 default, with evidence counts.', outcome: 'HANDLED' },
  { id: 'TR3', category: 'Explainability', title: 'A refusal is shown as an error rather than as a decision', expectation: 'A DENY traces to the rule that fired and states that no attempt was spent.', outcome: 'HANDLED' },
  { id: 'AT1', category: 'Attribution', title: 'Charges we make are recorded as the gateway default', expectation: 'Executed attempts carry initiated_by mandate_rescue and source executor.', outcome: 'HANDLED' },
  { id: 'AT2', category: 'Attribution', title: 'A recovered payment is filed under UNKNOWN and teaches the model that its bucket never recovers', expectation: 'A successful attempt inherits the bucket of the decline it recovered.', outcome: 'HANDLED' },
  { id: 'AT3', category: 'Attribution', title: 'A repeated payment id rewrites another mandate row', expectation: 'The upsert only updates a row belonging to the same subscription and cycle.', outcome: 'HANDLED' },
  { id: 'AT4', category: 'Attribution', title: 'Arm assignment is decided fresh on every run', expectation: 'Assignment is hash derived, recorded once, and stable even if the salt changes.', outcome: 'HANDLED' },
  { id: 'AT5', category: 'Attribution', title: 'The failure that opened the cycle is counted as a recovery attempt', expectation: 'The first attempt of a cycle is excluded from the per-attempt denominator.', outcome: 'HANDLED' },
  { id: 'PP1', category: 'Promise to pay', title: 'A customer says when they will have funds and nothing changes', expectation: 'An open promise moves the scheduled attempt to the promised date and the audit records why.', outcome: 'HANDLED' },
  { id: 'PP2', category: 'Promise to pay', title: 'Helm charges before the date the customer promised', expectation: 'The dispatcher waits rather than spending an attempt early.', outcome: 'HANDLED' },
  { id: 'PP3', category: 'Promise to pay', title: 'A customer promises a date in the past or beyond the mandate', expectation: 'Past dates, dates beyond the horizon, and dates after cancellation are refused.', outcome: 'HANDLED' },
  { id: 'PP4', category: 'Promise to pay', title: 'Changing the promised date leaves two live promises', expectation: 'Only one promise is open per cycle; the previous one is superseded and kept as history.', outcome: 'HANDLED' },
  { id: 'PP5', category: 'Promise to pay', title: 'A promise is marked kept by a payment that predates it', expectation: 'Only captures after the promise was made can settle it.', outcome: 'HANDLED' },
  { id: 'PP6', category: 'Promise to pay', title: 'A promise stays open forever', expectation: 'Once the date passes and a charge failed, it is settled as broken and becomes a reliability signal.', outcome: 'HANDLED' },
  { id: 'ML1', category: 'Language', title: 'A recovery message reaches an Indian customer only in English', expectation: 'English, Hinglish and Hindi templates exist and are chosen per customer.', outcome: 'HANDLED' },
  { id: 'ML2', category: 'Language', title: 'A translated message drops the opt-out or the promise option', expectation: 'Every language carries the amount, the link, a way to stop and a way to promise a date.', outcome: 'HANDLED' },
  { id: 'ML3', category: 'Language', title: 'An unknown language setting sends nothing at all', expectation: 'Unknown values fall back to English rather than failing.', outcome: 'HANDLED' },
  { id: 'OR1', category: 'Outreach', title: 'The system decides to contact a customer and never does', expectation: 'An allowed REAUTH_OUTREACH decision produces a real, expiring re-authorisation link.', outcome: 'HANDLED' },
  { id: 'OR2', category: 'Outreach', title: 'A customer is messaged twice for the same decision', expectation: 'Outreach is idempotent on the decision, and a repeat send is refused.', outcome: 'HANDLED' },
  { id: 'OR3', category: 'Outreach', title: 'A recovery message arrives in the middle of the night', expectation: 'Sends inside quiet hours are deferred to the next permitted window and nothing is written.', outcome: 'HANDLED' },
  { id: 'OR4', category: 'Outreach', title: 'A customer who opted out is contacted again', expectation: 'Opt-out blocks every future send and revokes outstanding links.', outcome: 'HANDLED' },
  { id: 'OR5', category: 'Outreach', title: 'Outreach continues after the kill switch is engaged', expectation: 'The kill switch blocks contact the same way it blocks a charge.', outcome: 'HANDLED' },
  { id: 'OR6', category: 'Outreach', title: 'A customer is contacted before the merchant granted write access', expectation: 'Contact requires the same consent gate as a money movement.', outcome: 'HANDLED' },
  { id: 'OR7', category: 'Outreach', title: 'A customer email or phone number is stored in the clear', expectation: 'Recipients are masked at rest, and the raw value is never persisted by outreach.', outcome: 'HANDLED' },
  { id: 'OR8', category: 'Outreach', title: 'The system reports a message as sent when nothing was delivered', expectation: 'Without a configured provider or contact details the row stays queued with the reason recorded.', outcome: 'HANDLED' },
  { id: 'OR9', category: 'Outreach', title: 'A re-authorisation link works forever', expectation: 'Every link expires, and never outlives the billing cycle it belongs to.', outcome: 'HANDLED' },
  { id: 'OR10', category: 'Outreach', title: 'A recovery link is guessable', expectation: 'Tokens are cryptographically random and unique across issuance.', outcome: 'HANDLED' },
  { id: 'MV1', category: 'Merchant value', title: 'A merchant is shown counts instead of money', expectation: 'The first screen after connecting is denominated in rupees from their own history.', outcome: 'HANDLED' },
  { id: 'MV2', category: 'Merchant value', title: 'Unmapped declines are quietly counted as recoverable revenue', expectation: 'Unclassified money is reported separately and excluded from the recoverable figure.', outcome: 'HANDLED' },
  { id: 'MV3', category: 'Merchant value', title: 'Hard declines are sold back to the merchant as recoverable', expectation: 'Hard buckets are excluded from the addressable figure.', outcome: 'HANDLED' },
  { id: 'MV4', category: 'Merchant value', title: 'A recovery rate is quoted from a sample too small to support it', expectation: 'A small sample is stated as a caveat on the report itself.', outcome: 'HANDLED' },
  { id: 'MV5', category: 'Merchant value', title: 'The parts of the loss do not add up to the loss', expectation: 'Addressable, hard and unclassified sum exactly to the money lost.', outcome: 'HANDLED' },
  { id: 'MV6', category: 'Merchant value', title: 'A merchant must grant write access before seeing any value', expectation: 'The whole report is produced from a read-only key.', outcome: 'HANDLED' },
  { id: 'Z1', category: 'Deployability', title: 'The marketing page is deleted by the app build', expectation: 'One build produces the landing page and the product together.', outcome: 'HANDLED' },
  { id: 'Z2', category: 'Deployability', title: 'A call to action on the landing page goes nowhere', expectation: 'Every landing call to action resolves to a real route.', outcome: 'HANDLED' },
  { id: 'Z3', category: 'Deployability', title: 'The landing page depends on a third party host for its assets', expectation: 'Every image is served from our own origin.', outcome: 'HANDLED' },
  { id: 'Z4', category: 'Deployability', title: 'The landing page is too heavy for Indian mobile data', expectation: 'Total image weight stays under a few megabytes.', outcome: 'HANDLED' },
  { id: 'Z5', category: 'Deployability', title: 'The start command runs without the credentials it needs', expectation: 'Local environment is loaded, and a missing key is stated rather than discovered later.', outcome: 'HANDLED' },
  { id: 'Z6', category: 'Deployability', title: 'The landing page states a fact the code contradicts', expectation: 'The rule count on the page is checked against the policy engine.', outcome: 'HANDLED' },
  { id: 'Y1', category: 'Gateway capability', title: 'The gateway advertises a rail it cannot actually perform', expectation: 'Capability is probed and reported per rail, and observed failures downgrade an advertised rail.', outcome: 'HANDLED' },
  { id: 'Y2', category: 'Gateway capability', title: 'An unactivated account is treated as ready because its rails look provisioned', expectation: 'No rail is reported usable while the account is unactivated.', outcome: 'HANDLED' },
  { id: 'Y3', category: 'Gateway capability', title: 'The capability probe claims readiness when the gateway is unreachable', expectation: 'An unreachable probe reports blocked, never ready.', outcome: 'HANDLED' },
  { id: 'Y4', category: 'Gateway capability', title: 'A rail that keeps failing inside the gateway keeps being retried', expectation: 'Attempts failing with error_source internal are excluded from the customer budget and surface as a failing rail.', outcome: 'HANDLED' },
  { id: 'Y5', category: 'Audit', title: 'A batch executes charges without recording the decisions behind them', expectation: 'Every execution intent carries the decision id that authorised it.', outcome: 'HANDLED' },
  { id: 'X1', category: 'Taxonomy evolution', title: 'A taxonomy version bump leaves history classified under the old version', expectation: 'Stored attempts are re-readable under the current taxonomy, not frozen at ingest time.', outcome: 'HANDLED' },
  { id: 'X2', category: 'Taxonomy evolution', title: 'Reclassification retroactively hands back a live attempt budget', expectation: 'A budget attribution change on an open cycle is refused unless explicitly allowed.', outcome: 'HANDLED' },
  { id: 'X3', category: 'Taxonomy evolution', title: 'A published recovery number changes with no way to explain why', expectation: 'Every bucket or budget change writes a before and after audit row.', outcome: 'HANDLED' },
  { id: 'X4', category: 'Taxonomy evolution', title: 'A gateway-side failure spends the customer\'s attempt budget', expectation: 'error_source internal and business are excluded from the budget, and only business is logged as our bug.', outcome: 'HANDLED' },
  { id: 'X5', category: 'Taxonomy evolution', title: 'Reclassifying twice double-counts the change', expectation: 'A second run scans zero rows and writes no further audit rows.', outcome: 'HANDLED' },
  { id: 'W1', category: 'De-confliction', title: 'Debits from different merchants colliding on one account', expectation: 'Detected per customer within a collision window, and spread across the day.', outcome: 'HANDLED' },
  { id: 'W2', category: 'De-confliction', title: 'Different customers treated as colliding because the times match', expectation: 'Collisions are per customer key only.', outcome: 'HANDLED' },
  { id: 'W3', category: 'De-confliction', title: 'A merchant dropped so another can be paid', expectation: 'Every debit keeps a slot; the resolution is positive sum.', outcome: 'HANDLED' },
  { id: 'W4', category: 'De-confliction', title: 'A debit moved outside its own permitted window', expectation: 'Each debit stays inside its own earliest and latest, and outside peak.', outcome: 'HANDLED' },
  { id: 'W5', category: 'De-confliction', title: 'A small debit taking the slot a large one needs', expectation: 'Largest first, because clearing a larger debit needs more residual balance.', outcome: 'HANDLED' },
  { id: 'W6', category: 'De-confliction', title: 'A debit forced into an illegal slot to clear a collision', expectation: 'Reported as unresolvable and left where it was.', outcome: 'HANDLED' },
  { id: 'W7', category: 'De-confliction', title: 'Customers matched across merchants by guesswork', expectation: 'Only an explicit customer key participates, and pooling is opt-in per merchant. Unkeyed mandates are excluded, not inferred.', outcome: 'HANDLED' },
  { id: 'W8', category: 'De-confliction', title: 'De-confliction claimed without the data to do it', expectation: 'The report states plainly when no mandate carries a cross-merchant key.', outcome: 'HANDLED' },
  { id: 'U1', category: 'Live batch', title: 'Policy and exactly-once proven only in separate suites', expectation: 'A batch that drives both together, asserting distinct keys equal intents equal orders.', outcome: 'HANDLED' },
  { id: 'U2', category: 'Live batch', title: 'A batch leaving intents unsettled', expectation: 'No intent left in INTENDED or SUBMITTED after the run.', outcome: 'HANDLED' },
  { id: 'U3', category: 'Live batch', title: 'The kill switch ignored at batch scale', expectation: 'Engaging it stops every attempt in the batch, verified.', outcome: 'HANDLED' },
  { id: 'U4', category: 'Live batch', title: 'One mandate exceeding the network budget under load', expectation: 'No subscription accumulates more intents than the budget allows.', outcome: 'HANDLED' },
  { id: 'V1', category: 'Bank holidays', title: 'A holiday calendar that is never populated', expectation: 'Seeded from a migration and loaded from the database, with a cache.', outcome: 'HANDLED' },
  { id: 'V2', category: 'Bank holidays', title: 'Shifting a UPI charge that never needed shifting', expectation: 'Only e-mandate shifts; UPI settles every day.', outcome: 'HANDLED' },
  { id: 'V3', category: 'Bank holidays', title: 'A charge shifted forward instead of back', expectation: 'The shift only ever moves earlier, matching the bank rule.', outcome: 'HANDLED' },
  { id: 'V4', category: 'Bank holidays', title: 'An uncovered year silently treated as holiday-free', expectation: 'Reported as not covered, and no shift applied rather than a wrong one.', outcome: 'HANDLED' },
  { id: 'V5', category: 'Bank holidays', title: 'A shift applied without the merchant being able to see it', expectation: 'The decision explanation is appended with the reason for the shift.', outcome: 'HANDLED' },
  { id: 'T1', category: 'Control plane', title: 'A raw-body parser for webhooks silently emptying every other POST body', expectation: 'The parser keeps the raw bytes and parses the JSON, so handlers still receive a body.', outcome: 'HANDLED' },
  { id: 'T2', category: 'Control plane', title: 'A request to release the kill switch engaging it instead', expectation: 'A false value survives parsing, and the release path is distinct from the engage path.', outcome: 'HANDLED' },
  { id: 'T3', category: 'Control plane', title: 'Anyone able to release the kill switch', expectation: 'Engaging needs nothing, releasing needs a configured token. Failing safe is free, failing open is not.', outcome: 'HANDLED' },
  { id: 'T4', category: 'Control plane', title: 'Releasing the kill switch when no token is configured at all', expectation: 'Refused, rather than defaulting to open.', outcome: 'HANDLED' },
  { id: 'S1', category: 'Subscriptions path', title: 'Assuming an issued invoice can be charged by API', expectation: 'Verified against the Invoice API: create, update, issue, delete, cancel, fetch, notify. No charge endpoint exists.', outcome: 'HANDLED' },
  { id: 'S2', category: 'Subscriptions path', title: 'A domestic card queued for a manual charge nobody can make', expectation: 'Marked unchargeable with the reason, and ranked last.', outcome: 'HANDLED' },
  { id: 'S3', category: 'Subscriptions path', title: 'An already-paid or expired invoice offered for charging', expectation: 'Assessed and excluded, with the reason recorded.', outcome: 'HANDLED' },
  { id: 'S4', category: 'Subscriptions path', title: 'The queue ordered arbitrarily rather than by value', expectation: 'Chargeable first, then expected value, then soonest.', outcome: 'HANDLED' },
  { id: 'S5', category: 'Subscriptions path', title: 'Subscriptions merchants left entirely unaddressed', expectation: 'A ranked, timed, reasoned charge queue plus the invoice notification the API does allow.', outcome: 'DETECTED', note: 'The queue and the notification action exist. The charge itself still requires a human to press Attempt Charge in the Razorpay dashboard, because no API for it exists. Recovery on this path is assisted, not automated, and the product should say so rather than imply otherwise.' },
  { id: 'Q1', category: 'Backfill', title: 'Only the last page of history fetched', expectation: 'Pagination walks until a short page, with skip advancing correctly.', outcome: 'HANDLED' },
  { id: 'Q2', category: 'Backfill', title: 'A misbehaving API looping forever', expectation: 'A page ceiling stops the walk.', outcome: 'HANDLED' },
  { id: 'Q3', category: 'Backfill', title: 'A rate limit aborting the whole backfill', expectation: 'Retries 429 and 5xx with backoff, gives up on 4xx.', outcome: 'HANDLED' },
  { id: 'Q4', category: 'Backfill', title: 'Backfilled history counted against a live attempt budget', expectation: 'Rows carry source backfill and counts_against_budget false.', outcome: 'HANDLED' },
  { id: 'Q5', category: 'Backfill', title: 'Re-running the backfill doubling the history', expectation: 'Deduplicated on the gateway payment id.', outcome: 'HANDLED' },
  { id: 'Q6', category: 'Backfill', title: 'A payment with nothing to group it under silently dropped', expectation: 'Skipped and counted, not silently discarded.', outcome: 'HANDLED' },
  { id: 'R1', category: 'Nightly sweep', title: 'Risk only detected after a charge fails', expectation: 'A forward sweep scores active mandates and flags expiry and degradation before any failure.', outcome: 'HANDLED' },
  { id: 'R2', category: 'Nightly sweep', title: 'The same mandate rescored on every tick', expectation: 'A minimum interval between scorings, honoured per mandate.', outcome: 'HANDLED' },
  { id: 'R3', category: 'Nightly sweep', title: 'One merchant sweep touching another merchant data', expectation: 'The sweep is scopeable per merchant.', outcome: 'HANDLED' },
  { id: 'R4', category: 'Nightly sweep', title: 'Sweeping mandates that are already halted or cancelled', expectation: 'Excluded by status.', outcome: 'HANDLED' },
  { id: 'R5', category: 'Nightly sweep', title: 'The injected clock disagreeing with the database clock', expectation: 'The sweep stamps scored_at with the clock it was given, so it stays replayable.', outcome: 'HANDLED' },
  { id: 'P1', category: 'CSV import', title: 'A quoted field containing a comma shifts every column', expectation: 'A real CSV parser, with quoted fields, escaped quotes and embedded newlines covered.', outcome: 'HANDLED' },
  { id: 'P2', category: 'CSV import', title: 'Excel byte order mark corrupting the first header', expectation: 'The BOM is stripped before the header is read.', outcome: 'HANDLED' },
  { id: 'P3', category: 'CSV import', title: 'A ragged row silently shifting values into the wrong columns', expectation: 'Refused with the line number, never partially applied.', outcome: 'HANDLED' },
  { id: 'P4', category: 'CSV import', title: 'A header we do not recognise dropped without trace', expectation: 'Unrecognised columns are listed in the report.', outcome: 'HANDLED' },
  { id: 'P5', category: 'CSV import', title: 'Rupee-formatted amounts read as paise', expectation: 'A decimal amount is converted, an integer is treated as paise, and an unreadable one skips the row.', outcome: 'HANDLED' },
  { id: 'P6', category: 'CSV import', title: 'Re-importing the same export doubling the history', expectation: 'Deduplicated on the gateway payment id.', outcome: 'HANDLED' },
  { id: 'P7', category: 'CSV import', title: 'Imported history counted against a live attempt budget', expectation: 'Imported rows carry counts_against_budget false.', outcome: 'HANDLED' },
  { id: 'P8', category: 'CSV import', title: 'An unknown decline code guessed into a bucket to look complete', expectation: 'Left UNKNOWN and reported, even when it makes the analysis look less finished.', outcome: 'HANDLED' },
  { id: 'N1', category: 'Evaluation', title: 'An off-policy estimate quoted from a deterministic logger', expectation: 'Refused outright, because deterministic logs carry no counterfactual information.', outcome: 'HANDLED' },
  { id: 'N2', category: 'Evaluation', title: 'An estimate dominated by a handful of high-weight rows', expectation: 'Effective sample size reported beside every estimate, with a floor below which it is not quoted.', outcome: 'HANDLED' },
  { id: 'N3', category: 'Evaluation', title: 'Unbounded importance weights blowing up the estimate', expectation: 'Weights clipped, and the number clipped is reported.', outcome: 'HANDLED' },
  { id: 'N4', category: 'Evaluation', title: 'No exploration, so no support ever accumulates', expectation: 'The allocator takes a non-first-choice slot on a configurable fraction of decisions and records the propensity.', outcome: 'HANDLED' },
  { id: 'N5', category: 'Evaluation', title: 'Exploration spending an attempt on an illegal slot', expectation: 'Exploration only ever picks among slots the allocator ranked, and the policy engine still checks the result.', outcome: 'HANDLED' },
  { id: 'N6', category: 'Evaluation', title: 'An off-policy number reported before any outcome settled', expectation: 'Reports no support and explains why, rather than printing a figure.', outcome: 'HANDLED' },
  { id: 'M1', category: 'Batch', title: 'Arms compared on different populations', expectation: 'Both arms run the identical mandate set, so the denominators match exactly.', outcome: 'HANDLED' },
  { id: 'M2', category: 'Batch', title: 'A result that cannot be reproduced', expectation: 'Fixed seed, deterministic across runs, asserted by test.', outcome: 'HANDLED' },
  { id: 'M3', category: 'Batch', title: 'Wait treated as give up', expectation: 'A HOLD advances the clock rather than abandoning the mandate.', outcome: 'HANDLED' },
  { id: 'M4', category: 'Batch', title: 'A worse halt rate hidden behind a better efficiency number', expectation: 'The tradeoff is computed and printed, with the lifetime cost against the efficiency gain.', outcome: 'HANDLED' },
  { id: 'M5', category: 'Batch', title: 'A hardcoded conclusion contradicting the computed numbers', expectation: 'Favourable or unfavourable is derived, and a test asserts exactly one appears.', outcome: 'HANDLED' },
  { id: 'M6', category: 'Batch', title: 'Simulated numbers presented as real', expectation: 'Labelled simulated in the first two hundred characters, with the generative model printed in full.', outcome: 'HANDLED' },
  { id: 'M7', category: 'Batch', title: 'The batch never ran through the real executor', expectation: 'A live batch drives every attempt through intent rows, idempotency keys and settlement, asserting one order per attempt.', outcome: 'HANDLED' },
  { id: 'L1', category: 'Gateway', title: 'A live key used while the mode says test', expectation: 'Refuse at construction rather than charging real money in a test run.', outcome: 'HANDLED' },
  { id: 'L2', category: 'Gateway', title: 'A test key used while the mode says live', expectation: 'Refuse at construction.', outcome: 'HANDLED' },
  { id: 'L3', category: 'Gateway', title: 'Charging a subscription with no recurring token recorded', expectation: 'Raise before any HTTP call is made.', outcome: 'HANDLED' },
  { id: 'L4', category: 'Gateway', title: 'A duplicate receipt rejection mistaken for a generic error', expectation: 'Mapped to DuplicateReceiptError so the executor reconciles instead of retrying.', outcome: 'HANDLED' },
  { id: 'L5', category: 'Gateway', title: 'An unparseable response body returning undefined', expectation: 'Raises a typed error rather than proceeding on nothing.', outcome: 'HANDLED' },
  { id: 'L6', category: 'Gateway', title: 'Credentials leaking into a URL or a log line', expectation: 'Auth travels in a header only, and the logger redacts secrets.', outcome: 'HANDLED' },
  { id: 'L7', category: 'Gateway', title: 'Rupee floats sent where paise integers are required', expectation: 'Amount asserted to be an integer in paise.', outcome: 'HANDLED' },
  { id: 'K1', category: 'Backtest', title: 'The liquidity model sees payments from after the decision point', expectation: 'The loader refuses any row at or after the cutoff.', outcome: 'HANDLED' },
  { id: 'K2', category: 'Backtest', title: 'A row exactly at the cutoff leaks in', expectation: 'The cutoff is exclusive, and a test covers the boundary.', outcome: 'HANDLED' },
  { id: 'K3', category: 'Backtest', title: 'The same attempt counted once per failure that precedes it', expectation: 'Attempts are deduplicated by id, not summed per decision point.', outcome: 'HANDLED' },
  { id: 'K4', category: 'Backtest', title: 'A timing adjustment reported as a refusal', expectation: 'A defer that only moves the clock still authorises the attempt.', outcome: 'HANDLED' },
  { id: 'K5', category: 'Backtest', title: 'An approved non-retry action reported as a rule refusal', expectation: 'Labelled by the action chosen, never by R-OK.', outcome: 'HANDLED' },
  { id: 'K6', category: 'Backtest', title: 'The report claims a recovery figure it cannot support', expectation: 'It states plainly that history holds no outcome for an attempt never made.', outcome: 'HANDLED' },
  { id: 'K7', category: 'Backtest', title: 'A weak timing model presented as a working one', expectation: 'The report says so when most decisions fell back to a population default.', outcome: 'HANDLED' },
  { id: 'I1', category: 'Fixes', title: 'A paid cycle is described as out of attempts instead of paid', expectation: 'R-PAID outranks R-BUDGET so the merchant sees the true reason.', outcome: 'HANDLED' },
  { id: 'I2', category: 'Fixes', title: 'The chronic-decline limit cannot be switched off', expectation: 'Setting the limit to zero disables the rule.', outcome: 'HANDLED' },
  { id: 'I3', category: 'Fixes', title: 'A bank holiday shift silently changes the time of day', expectation: 'The shift preserves the time and records what it did.', outcome: 'HANDLED' },
  { id: 'I4', category: 'Fixes', title: 'Every Saturday treated as a bank holiday', expectation: 'Only the second and fourth Saturday, plus every Sunday.', outcome: 'HANDLED' },
  { id: 'G1', category: 'Stale decisions', title: 'Timing rules re-checked at execution would always fail', expectation: 'The notification lead time was satisfied when the attempt was scheduled, so it is not re-checked.', outcome: 'HANDLED' },
  { id: 'G2', category: 'Stale decisions', title: 'A revoked decision is picked up again on the next pass', expectation: 'The original decision is marked revoked so it is not re-selected.', outcome: 'HANDLED' },
  { id: 'G3', category: 'Stale decisions', title: 'The reason an attempt was cancelled is not visible to the merchant', expectation: 'The revocation is written as its own decision row with the rule that stopped it.', outcome: 'HANDLED' },
  { id: 'F10', category: 'Policy and agent', title: 'Dry run bypassed at one call site', expectation: 'Enforced inside the executor so no call site can bypass it.', outcome: 'HANDLED' },
];

export function scorecard(scenarios: Scenario[] = SCENARIOS) {
  const counts = { HANDLED: 0, DETECTED: 0, UNHANDLED: 0 };
  for (const s of scenarios) counts[s.outcome] += 1;
  return { total: scenarios.length, ...counts };
}
